/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/desks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Desks and whether they are free on a given date */
        get: operations["listDesks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book a desk for a date */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a booking */
        delete: operations["cancelBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Desk: {
            /** Format: uuid */
            id: string;
            /** @description What is printed on the desk, e.g. "A-14". */
            label: string;
            zone: components["schemas"]["Zone"];
            /** @description Free on the requested date. */
            available: boolean;
        };
        /** @enum {string} */
        Zone: "quiet" | "collaboration" | "lab";
        BookingRequest: {
            /** Format: uuid */
            deskId: string;
            /** Format: date */
            date: string;
            /**
             * Format: email
             * @description The email of the person the desk is for.
             */
            bookedBy: string;
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            deskId: string;
            /** Format: date */
            date: string;
            /** Format: email */
            bookedBy: string;
            /** @enum {string} */
            status: "confirmed" | "cancelled";
        };
        /** @description RFC 9457 problem details, trimmed to what this API uses. */
        Problem: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Field-level validation failures, when there are any. */
            errors?: {
                field: string;
                message: string;
            }[];
        };
    };
    responses: {
        /** @description The request was not valid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDesks: {
        parameters: {
            query: {
                /** @description The day to check, in the workspace's local calendar. */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every desk, with availability for that date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Desk"][];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description The booking was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description That desk is already booked for that date. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled. Cancelling an already cancelled booking is not an error. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No booking with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
